# Generated by Django 2.0.9 on 2018-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20180108_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('complete', 'complete')], max_length=256, null=True),
        ),
    ]
